# Generated by Django 5.0.6 on 2024-05-17 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=26, unique=True)),
                ('main_translation', models.CharField(max_length=50)),
                ('accepted_translation', models.JSONField()),
                ('word_type', models.CharField(max_length=10)),
                ('verb_type', models.IntegerField(blank=True, null=True)),
                ('verb_tense', models.CharField(blank=True, max_length=8, null=True)),
                ('gender', models.CharField(blank=True, max_length=3, null=True)),
                ('need_moderation', models.BooleanField(default=False)),
                ('moderated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verb_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.word')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26, unique=True)),
                ('is_verb', models.BooleanField(default=False)),
                ('need_moderation', models.BooleanField(default=False)),
                ('moderated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='games.word')),
            ],
        ),
    ]
