# Generated by Django 5.0.6 on 2024-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_word_accepted_translation_alter_word_word_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='accepted_translation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
