# Generated by Django 5.0.6 on 2024-07-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_word_accepted_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Masculino'), ('f', 'Femenino'), ('mf', 'Both')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='verb_tense',
            field=models.CharField(blank=True, choices=[('present', 'present'), ('past', 'past'), ('future', 'future'), ('potent', 'Potentional')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='verb_type',
            field=models.IntegerField(blank=True, choices=[('0', 'Infinitivo'), ('1', 'Primera singular'), ('2', 'Segunda singular'), ('3', 'Tercera singular'), ('4', 'Primera plural'), ('5', 'Segunda plural'), ('6', 'Tercera plural')], null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('noun', 'Noun'), ('adjective', 'Adjective'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('pronoun', 'Pronoun')], max_length=11),
        ),
    ]
